language: node_js
node_js:
- 6.10.0
script:
- npm install
after_success:
- sed -i'' "/^ *repo/s~github\.com~${git_token}@github.com~" _config.yml
- hexo cl
- hexo g
- hexo deploy
before_install:
- openssl aes-256-cbc -K $encrypted_ee0b21f4d10e_key -iv $encrypted_ee0b21f4d10e_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "hadesshark"
- git config --global user.email "hades_shark@hotmail.com"
- npm install -g hexo-cli
env:
  global:
    secure: a7Qh1EI4EcNVrUkMdxGQPBuCi1MYLG6MGKqOESaODc33oufSdszGmcYFCnog3rHstuXLaGSvMFxFiEBLpkBkaFDRY1rKeMTJGul80GQY3Zl1jz74m36zQmpQjU8avdTZxfhO3MRMroyMD1QKu8Nbr+E5pjytciwlKFpyz9xN64MRl92n+DbTu9LubWmZtO99G4gnSy80QTP5pIe/gUNxxguSnETXE84ZHP/UO1yFut9It06WDzyFzGtk2Zs9doXTTGFJuJ7Q+BhondhwILRny2PVxHX3ic7sIQi05qZKBrdHqnK/FZAXj+NJ5t6+P3xP+qHyF2pP2HF0bpvwTFAISUHjcJCMq7JilsRBUoR+Iwez8oBxYF5jqQpyJIUM1kUm5GFh6iyPDIvtjMe1p34vH46f2wxaSExPc168POKszcMqEVf9GA9h71pj9oX9sS6fM7L7aJpuHhoVQzC4iF+nnJfZ+HSlZWJRJnoLmZ/w80a8T0m0znY5bw24NoOhl2AqIzFeXOqtpFvGsWIJ5HahXLXjoZfsoR867zIOW1WyykKuAf+RBDtdyMXKFOvB4N2u/ODYwIzHCTUh/ciuwi+dWv4W/Mm+Iafji76UJEclr1JO5j43MN2YUGZH2SHxY1GOw11wcjcJaed/lVXNPUjlaLq5vHcZJbgrCQ5q0QYOZVg=
